CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	content TEXT NOT NULL,
	image_url TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
	id SERIAL PRIMARY KEY,
	tag_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE post_tags(
	post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
	tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE,
	PRIMARY KEY (post_id, tag_id)
);